spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sudiptanar/hotel-rating-service-config.git
          clone-on-start: true
server:
  port: 8085